### ISSUE TITLE
[SHM] Issues during installation

### ISSUE THREAD

**Issue by KarolAntczak** [defenselayers/manuals#1]
Hi, 

several issues I encountered during installation of [shm](https://github.com/defenselayers/shm) . I was able to resolve them, but I think it would be great if you could mention them in manual:
- `pip install .` did not worked on my machine since `pip` uses Python 2.7 by default ( I am using Ubuntu 18.04). I had to install and use `pip3` instead
-  After the installation, calling `shm` command yieds "Command 'shm' not found, did you mean:" I had to update PATH this way: `python3.6 -m site &> /dev/null && PATH="$PATH:'python3.6 -m site --user-base'/bin"`

**Comment by alekpc** [comment]
Hi,
Thank you for comments. As a rule we are not developing software for unsupported Python 2.x and we require Python 3 - this is clearly stated in `README.md` together with `pip3` package requirement. Indeed pip3 on some distros is named pip and on others pip3. The name of pip can be also influence by how it has been installed in the system. 

As for path update issue we will update `README.md` to advise installation in `virtualenv`. This is straightforward process since Python 3 comes with `venv` package.

**Comment by KarolAntczak** [comment]
Great, thanks!
